#include "Globals.h"

// Copied from SQLSRV32
#define SETFUNCBIT(func) (1 << (func&0xf))
static UWORD wCoreAPI[] =
{   //  Original CORE APIs
    //  SETFUNCBIT(0), |                            //  0-15
    //  SETFUNCBIT(SQL_API_SQLALLOCCONNECT) |
    //  SETFUNCBIT(SQL_API_SQLALLOCENV) |
    //  SETFUNCBIT(SQL_API_SQLALLOCSTMT) |
    SETFUNCBIT(SQL_API_SQLBINDCOL) |
    SETFUNCBIT(SQL_API_SQLCANCEL) |
    SETFUNCBIT(SQL_API_SQLCOLATTRIBUTE) |
    SETFUNCBIT(SQL_API_SQLCONNECT) |
    SETFUNCBIT(SQL_API_SQLDESCRIBECOL) |
    SETFUNCBIT(SQL_API_SQLDISCONNECT) |
    //  SETFUNCBIT(SQL_API_SQLERROR) |
    SETFUNCBIT(SQL_API_SQLEXECDIRECT) |
    SETFUNCBIT(SQL_API_SQLEXECUTE) |
    SETFUNCBIT(SQL_API_SQLFETCH),
    //  SETFUNCBIT(SQL_API_SQLFREECONNECT) |
    //  SETFUNCBIT(SQL_API_SQLFREEENV),

    SETFUNCBIT(SQL_API_SQLFREESTMT) |           // 16-31
    SETFUNCBIT(SQL_API_SQLGETCURSORNAME) |
    SETFUNCBIT(SQL_API_SQLNUMRESULTCOLS) |
    SETFUNCBIT(SQL_API_SQLPREPARE) |
    SETFUNCBIT(SQL_API_SQLROWCOUNT) |
    SETFUNCBIT(SQL_API_SQLSETCURSORNAME) |
    SETFUNCBIT(SQL_API_SQLBULKOPERATIONS),
    //  SETFUNCBIT(SQL_API_SQLSETPARAM) |
    //  SETFUNCBIT(SQL_API_SQLTRANSACT),

    SETFUNCBIT(SQL_API_SQLCOLUMNS) |            // 32-47
    SETFUNCBIT(SQL_API_SQLDRIVERCONNECT) |
    SETFUNCBIT(SQL_API_SQLGETCONNECTOPTION) |
    SETFUNCBIT(SQL_API_SQLGETDATA) |
    SETFUNCBIT(SQL_API_SQLGETFUNCTIONS) |
    SETFUNCBIT(SQL_API_SQLGETINFO) |
    //  SETFUNCBIT(SQL_API_SQLGETSTMTOPTION) |
    SETFUNCBIT(SQL_API_SQLGETTYPEINFO),

    SETFUNCBIT(SQL_API_SQLPARAMDATA) |          // 48-63
    SETFUNCBIT(SQL_API_SQLPUTDATA) |
    SETFUNCBIT(SQL_API_SQLSETCONNECTOPTION) |
    //  SETFUNCBIT(SQL_API_SQLSETSTMTOPTION) |
    SETFUNCBIT(SQL_API_SQLSPECIALCOLUMNS) |
    SETFUNCBIT(SQL_API_SQLSTATISTICS) |
    SETFUNCBIT(SQL_API_SQLTABLES) |
    SETFUNCBIT(SQL_API_SQLBROWSECONNECT) |
    SETFUNCBIT(SQL_API_SQLCOLUMNPRIVILEGES) |
    //  SETFUNCBIT(SQL_API_SQLDATASOURCES) |
    SETFUNCBIT(SQL_API_SQLDESCRIBEPARAM) |
    SETFUNCBIT(SQL_API_SQLEXTENDEDFETCH) |
    SETFUNCBIT(SQL_API_SQLFOREIGNKEYS) |
    SETFUNCBIT(SQL_API_SQLMORERESULTS) |
    SETFUNCBIT(SQL_API_SQLNATIVESQL) |
    SETFUNCBIT(SQL_API_SQLNUMPARAMS),

    SETFUNCBIT(SQL_API_SQLPARAMOPTIONS) |       // 64-79
    SETFUNCBIT(SQL_API_SQLPRIMARYKEYS) |
    SETFUNCBIT(SQL_API_SQLPROCEDURECOLUMNS) |
    SETFUNCBIT(SQL_API_SQLPROCEDURES) |
    SETFUNCBIT(SQL_API_SQLSETPOS) |
    SETFUNCBIT(SQL_API_SQLSETSCROLLOPTIONS) |
    SETFUNCBIT(SQL_API_SQLTABLEPRIVILEGES) |
    //  SETFUNCBIT(SQL_API_SQLDRIVERS) |
    SETFUNCBIT(SQL_API_SQLBINDPARAMETER) |
    SETFUNCBIT(SQL_API_SQLNEXTCOLUMN),
    //  SETFUNCBIT(0), |
    //  SETFUNCBIT(0), |
    //  SETFUNCBIT(0), |
    //  SETFUNCBIT(0), |
    //  SETFUNCBIT(SQL_API_SQLALLOCHANDLESTD),
};

static UWORD wXOpenAPI[] =
{   //  XOpen (ODBC 3.0) APIs
    SETFUNCBIT(SQL_API_SQLALLOCHANDLE) |        // 992-1007
                                                //  SETFUNCBIT(SQL_API_SQLBINDPARAM) |
    SETFUNCBIT(SQL_API_SQLCLOSECURSOR) |
    SETFUNCBIT(SQL_API_SQLCOPYDESC) |
    SETFUNCBIT(SQL_API_SQLENDTRAN) |
    SETFUNCBIT(SQL_API_SQLFREEHANDLE) |
    SETFUNCBIT(SQL_API_SQLGETCONNECTATTR),

    SETFUNCBIT(SQL_API_SQLGETDESCFIELD) |       // 1008-1023
    SETFUNCBIT(SQL_API_SQLGETDESCREC) |
    SETFUNCBIT(SQL_API_SQLGETDIAGFIELD) |
    SETFUNCBIT(SQL_API_SQLGETDIAGREC) |
    SETFUNCBIT(SQL_API_SQLGETENVATTR) |
    SETFUNCBIT(SQL_API_SQLGETSTMTATTR) |
    SETFUNCBIT(SQL_API_SQLSETCONNECTATTR) |
    SETFUNCBIT(SQL_API_SQLSETDESCFIELD) |
    SETFUNCBIT(SQL_API_SQLSETDESCREC) |
    SETFUNCBIT(SQL_API_SQLSETENVATTR) |
    SETFUNCBIT(SQL_API_SQLSETSTMTATTR) |
    SETFUNCBIT(SQL_API_SQLFETCHSCROLL)
};
// Update a bit in functions map
__inline void UpdateFuncBit(UWORD *lpbFunc, UWORD fFunction, BOOL f)
{
    UWORD uwWord;
    UWORD uwBit;
    LPWORD lpWord;

    uwWord = fFunction >> 4; // / 16
    uwBit = fFunction & 0xf;

    lpWord = lpbFunc + uwWord;
    if (f)
        *lpWord |= ((UWORD)1 << uwBit);
    else
        *lpWord &= ~((UWORD)1 << uwBit);
}

SQLRETURN  SQL_API SQLGetFunctions(SQLHDBC ConnectionHandle,
    SQLUSMALLINT FunctionId,
    _Out_writes_opt_(_Inexpressible_("Buffer length pfExists points to depends on fFunction value."))
    SQLUSMALLINT *Supported)
{
    switch (FunctionId)
    {
    case SQL_API_ODBC3_ALL_FUNCTIONS:
        if (Supported)
        {
            memset(Supported, 0, sizeof(UWORD) * 250);
            memcpy(Supported + (SQL_API_SQLALLOCCONNECT >> 4),
                wCoreAPI, sizeof(wCoreAPI));
            memcpy(Supported + (SQL_API_SQLALLOCHANDLE >> 4),
                wXOpenAPI, sizeof(wXOpenAPI));
            UpdateFuncBit(Supported, SQL_API_SQLSETPOS, TRUE);
            UpdateFuncBit(Supported, SQL_API_SQLNEXTCOLUMN, TRUE);
            break;
        }
        else
        {
            return SQL_ERROR;
        }
        break;
    default:
        TestTrace(TEXT("SQLGetFunctions not implemented for this case"));
        return SQL_ERROR;
    }
    return SQL_SUCCESS;
}